### ISSUE TITLE
地址偏移问题

### ISSUE THREAD

**Issue by chrisxvin** [oasisfeng/google-maps-sdk-rectify#3]
在6.0.1系统上，使用了纠偏之后，地图显示的当前位置对了，但是查询出来的地址都偏移了。
请看附件图片。定位在世纪公园，但是查询到的周边地址却是东南角的一片。
![screenshot_20170225-081616](https://cloud.githubusercontent.com/assets/628293/23326136/e7179886-fb35-11e6-99a9-876da2b4fa2a.png)
![screenshot_20170225-084055](https://cloud.githubusercontent.com/assets/628293/23326167/2a903136-fb36-11e6-9557-db93f1c0aaf8.png)

**Comment by oasisfeng** [comment]
抱歉，这个项目已不再维护了。
